#!/usr/bin/env Rscript
## R-Forge build system tool chain
## update and print package status

require("rfTools")

## read connection information
conf_file <- "/home/rforge/conf/rf.conf"
rfc <- rf_read_configuration( file = conf_file )

## we use some caching here
pkg_status_cache <- file.path( rfTools:::.rf_get_tmp(rfc), "pkg_status_cache.rda" )
if( !file.exists(pkg_status_cache) ){
  pkg_status <- rf_pkg_status(rfc)
  save(pkg_status, file = pkg_status_cache)
}
load( pkg_status_cache )

## update package db: outdated and brandnew packages => status 1 (scheduled for build)
tobuild <- rf_prepare_build(rfc, pkg_status)
## export sources and make them available for build
rf_export_and_build_pkgs( rfc, pkg_status, tobuild )

writeLines("The following packages are scheduled for build:")
tobuild
