#!/usr/bin/env Rscript
## R-Forge build system tool chain
## update and print package status

## from CRAN-package-list:

## We really want to run in a UTF-8 locale ...
lc_ctype <- Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
## We used to do:
## But sort in the C locale.
##   lc_collate <- Sys.setlocale("LC_COLLATE", "C")
## But as package names must be unique *ignoring* case, it seems more
## appropriate to also sort ignoring case.  Hence:
lc_collate <- Sys.setlocale("LC_COLLATE", "en_US.UTF-8")

.libPaths("/home/rforge/lib/R")

require("rfTools")

## read connection information
conf_file <- "/home/rforge/conf/rf.conf"
rfc <- rf_read_configuration( file = conf_file )

## we use some caching here
pkg_status_cache <- file.path( rfTools:::.rf_get_tmp(rfc), "pkg_status_cache.rda" )
if( !file.exists(pkg_status_cache) ){
  pkg_status <- rf_pkg_status(rfc)
  save(pkg_status, file = pkg_status_cache)
}
load( pkg_status_cache )

writeLines(sprintf("R-Forge build system status (%s)", Sys.time()))
writeLines("- Current R and rfTools version:")
R.version.string
sprintf("rfTools version %s", packageDescription("rfTools")$Version)

malformed <- lapply(pkg_status$malformed_description, function(x) x$sanity_check$msg)
if( length(malformed) ){
  reponames <- unlist(lapply(pkg_status$malformed_description, function(x) x$repo))
  names(malformed) <- reponames
  
  writeLines("- Projects containing packages with a malformed DESCRIPTION file:")
           
  print(malformed)
}

writeLines("- Packages currently being built:")
rownames(pkg_status$db)[pkg_status$db[, "status"] %in% c(1,2)]

len_outdated <- length(rownames(pkg_status$db)[pkg_status$db[, "status"] == 5])
if(len_outdated){
  writeLines(sprintf("- %d packages are up-to-date and %d offline.", length(rownames(pkg_status$db)[pkg_status$db[, "status"] %in% c(0)]), len_outdated))
} else {
  writeLines(sprintf("- %d packages are up-to-date.", length(rownames(pkg_status$db)[pkg_status$db[, "status"] %in% c(0)])))
}

#writeLines("- Packages marked as 'Offline':")
#rownames(pkg_status$db)[pkg_status$db[, "status"] == 5]
