#!/bin/sh
# /etc/init.d/rserve starts an R daemon to be used on R-Forge check machines
#

. /lib/lsb/init-functions

## Variables
LOGFILE="/srv/R/tmp/Rserv/rserve.log"
PIDFILE="/var/run/rserve.pid"
CONFIGFILE="/etc/Rserv.conf"
DAEMON="/usr/bin/R"
RSERVE="CMD Rserve"

test -f $CONFIGFILE || exit 0
test -x $DAEMON || exit 0

stop_rserve()
{
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
}

start_rserve()
{
    start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $RSERVE;
}

case "$1" in
  start)
	log_daemon_msg "Starting rserve"
	if start_rserve ; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
    stop)
	log_daemon_msg "Stopping rserve"
	if stop_rserve; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  restart)
    log_daemon_msg "Stopping rserve for restart"
    # regenerate exim4.conf
    stop_rserve
    log_end_msg 0
    sleep 2
    log_daemon_msg "Restarting rserve"
    start_rserve
    log_end_msg 0
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
