* News (Front page)
** Maintenance Work - Disk Space Expansion
Dear R-Forge users,

Please note the short (<30min.) R-Forge downtime today at 18:00 CET.

Details:

We need to extend disk space of the system hosting the core R-Forge
components. This will lead to a short (<30min.) downtime of R-Forge
today at 18:00 CET. This is necessary due to the unreliability of
R-Forge especially on weekends, when log files have to be copied to a
backup location. 

We are sorry for the inconvenience caused.

Best regards,
The R-Forge Administration and Development Team

** R-Forge Update (2009-12-10)

   We made the following changes and updates to the R-Forge system:
   
   - Added a graphic showing the stages of the package build and check
     system (http://site.r-forge.r-project.org/).
   - Added a globlal check flag. Packages hosted on R-Forge are now
     checked using "--no-examples --no-tests --no-vignettes" as
     additional flags to R CMD check due to the heavy compute time
     needed for a complete run. Developers may apply that their 
     packages are listed in a so-called white list to enable run-time
     checks again. More details will follow.
   - RForgeTools updated to 0.4-4: This update includes a lot of small
     fixes regarding package dependencies and their
     installation. Furthermore, packages are only built if the SVN
     revision changes, otherwise the previous tarball or binary
     is kept.

   Best regards,
   The R-Forge Administration and Development Team

** First issue of The R Journal & R-Forge paper (2009-05-29)
   The first issue of The R Journal (successor of R News) has now been
   published at http://journal.R-project.org/ . (See full announcement:
   https://stat.ethz.ch/pipermail/r-announce/2009/000502.html ).

   This issue features a special section with invited papers on the
   future of R, including an introduction to R-Forge. Among others, this
   paper provides a hands-on tutorial for new users to become familiar
   with the core features of R-Forge.

   Best regards, 
   The R-Forge Administration and Development Team

** R-Forge Update, Windows builds online
   We made the following changes and updates to the R-Forge system:

   - The Windows build machine is online again
   - MacTex installation on Mac builder
   - RForgeTools updated to 0.3-7: R CMD check is now checking the
     package tarball if it is available. This solves some issues
     (warnings) with packages containing vignettes.

   Best regards,
   The R-Forge Administration and Development Team

** Maintenance work - build/check machines (Windows)
   Windows build machines temporarily offline due to maintenance
   work. This means that binary packages are currently not up-to-date. We
   are sorry for the inconvenience caused.

   Best regards,
   The R-Forge Administration and Development Team

** R-Forge Update (2009-04-16)
   We are pleased to see that R-Forge has more than 1000
   registered users now. What's more, around 350 projects and
   almost 400 hosted packages show that there is great interest in
   R-Forge among the R community. And these numbers are constantly
   increasing. 
   
   We made the following changes and updates to the R-Forge system:
   
   - R-Forge packages now additionally include the following meta
     information in DESCRIPTION files:
       - Repository: R-Forge
       - Repository/R-Forge/Project: <project_unix_name>
       - Repository/R-Forge/Revision: <revision_in_SVN>
       - Publication/Date: <commit_date>
     Note that this information is added on the serverside. If the
     tags already exist they get overwritten. Nevertheless, you may
     want to include this information in your DESCRIPTION file if you
     submit your package to CRAN via the non-R-Forge way (the ftp
     upload). CRAN uses/will use the information to automatically provide
     some info (like the link to the R-Forge project) on the package
     web sites.
   - RForgeTools updated to 0.3-6: resolve Omegahat package
     dependencies, help files, minor fixes.

   Best regards,
   The R-Forge Administration and Development Team

** R-Forge Update: Minor Improvements (2009-02-02)
   Today we improved the package build system.
   - closed [#262] we added support to Brian Ripley's Windows packages repository
     http://r-forge.r-project.org/tracker/index.php?func=detail&aid=262&group_id=34&atid=196 
   - fixed some lines in RForgeTools (now version 0.3-2). Resolving
     dependencies (Depends + Suggests in DESCRIPTION) works better
     now.
   - MacOSX: switched back to universal binaries (default R on CRAN
     is a Tiger build).

   Best,
   Stefan

** R-Forge New Year Update (2009-01-12)

   The R-Forge Development and Administration Team wishes the whole R community a happy new year. The first update in 2009 includes:
   - a new documentation section on the home page,
   - a link on the home page to a short introduction to the R-Forge system. The title of this paper is "Collaborative Software Development Using R-Forge".
   - R-devel package checking for all platforms (Mac OSX coming soon). Furthermore experimental R-devel binaries for Windows are available. Take care!
   
   Furthermore, RForgeTools have been updated to version 0.3-1 which delivers,
   - a new field "Revision" in the PACKAGES file in all R-Forge contrib directories. You can use e.g. the command available.packages(contriburl = contrib.url("http://r-forge.r-project.org";), fields = "Revision") directly in R to additionally retrieve the SVN revision of the packages on R-Forge,
   - an improved build/check system (support of R-devel),
   - and a revision-based package building system leading to faster availability of package binaries.
   
   Regards,
   Stefan

** Mailing List Improvements (2008-11-28)

   Several mailing list issues have been fixed or improved in the last couple of days:
   
   - I've fixed a problem with list admin mails not being delivered. As some of you may already have noticed, those notifications now work properly.
   
   - As a side effect, mails to &lt;username&gt;@users.r-forge.r-project.org are now properly forwarded.
   
   - There is now an option to generate a new password for mailing list administration, in case you cannot recall your old one. Just go to the List -> Admin tab and click "Generate New Password".
   
   - Automated commit mails are now truncated to be smaller than 40kB. This way they do not get caught in Mailman's size filter and don't require authorization by the list admin.

   Regards
   Martin

** Minor Fixes to R-Forge System (2008-11-22)
Closed the following bugs/requests:

- X11 on Mac (Support #249)
http://r-forge.r-project.org/tracker/index.php?func=detail&aid=249&group_id=34&atid=194
- Added support for ssh on port 23 (Feature Req. #108)
http://r-forge.r-project.org/tracker/index.php?func=detail&aid=108&group_id=34&atid=196

st

** Additional Software on Windows Server (2008-11-18)

   Today I additionally installed
   - JAVA SE JDK 1.6 Update 10
   - GTK+ from SourceForge.net
   on the Windows build/check server.

   Happy forging,
   Stefan

** Updates on R-Forge (2008-11-10)

   Last week we updated the build/check system. The following changes
   were made:

*** new field "Revision" in DESCRIPTION files.
    R-Forge packages now include this field which is automatically generated upon checkout.
    
*** log files include additional information 
    like the R version used to build the package.

*** Bioconductor dependencies are now resolved correctly.
*** an additional link for each package in the 'R packages' tab points to the CRAN web area of the corresponding package (if it exists).

   Best regards,
   The R-Forge Administration and Development Team


